window.alert("Hi window, this alert is form Murtaza");

console.log("Hi console, this log is from Murtaza");
console.warn("Hi console, this warning is from Murtaza");
console.error("Hi console, this error is from Murtaza");

window.document.getElementById('myHead1').innerText = "Welcome to my Website";
window.document.getElementById('p1').innerText = "This paragraph is generated by JS.";
window.document.write("Hi document, this is me Murtaza");